import time
from selenium import webdriver
from selenium.webdriver.common.by import By

driver=webdriver.Chrome()
driver.get("https://login.yahoo.com/?.src=ym&pspid=159600001&activity=mail-direct&.lang=en-IN&.intl=in&.done=https%3A%2F%2Fmail.yahoo.com%2Fd")
driver.maximize_window()
time.sleep(7)

driver.find_element(By.NAME,"username").send_keys('karthik01@myyahoo.com')
driver.find_element(By.NAME,"signin").click()
time.sleep(3)
driver.find_element(By.ID,"login-passwd").send_keys('kumar#123')
driver.find_element(By.ID,"login-signin").click()
time.sleep(3)
driver.find_element(By.LINK_TEXT,"Compose").click()
time.sleep(3)
driver.find_element(By.XPATH,"//*[@id='message-to-field']").send_keys('ugarjurmath07@yahoo.com')
time.sleep(2)
driver.find_element(By.XPATH,"//input[@data-test-id='compose-subject']").send_keys('Hi how are you')
driver.find_element(By.XPATH,"//*[@data-test-id='compose-send-button']").click()
time.sleep(2)
driver.find_element(By.ID,"ybarAccountMenuOpener").click()
time.sleep(3)
driver.find_element(By.ID,"profile-signout-link").click()
time.sleep(3)
driver.find_element(By.LINK_TEXT,"Sign In").click()
time.sleep(3)
driver.find_element(By.LINK_TEXT,"Use another account").click()
time.sleep(3)
driver.find_element(By.NAME,"username").send_keys('ugarjurmath07@yahoo.com')
driver.find_element(By.NAME,"signin").click()
time.sleep(3)
driver.find_element(By.ID,"login-passwd").send_keys('uday@07')
driver.find_element(By.ID,"login-signin").click()
time.sleep(3)
driver.find_element(By.XPATH,"//div[@class='icon mail']").click()
time.sleep(4)
